### ISSUE TITLE
Favourite Wishlist

### ISSUE THREAD

**Issue by Toterino** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#163]
As a homebuyer, I want to be able to create a wishlist of my favourite properties so that I can easily keep track of the ones I'm interested in.

Acceptance Criteria:

- When I am a buyer, I want to have the option to favourite a property.
- When I am a guest user, I do not have the option to favourite a property.
- If I have an account, I want the ability to display the properties that I have favourited previously

Task breakdown:
- [ ] #165 Create a button (heart or star shaped) on each house template 
- [ ] #166 The favourite button only appears if the user is signed in.
- [ ] #167 When clicking on "My Favourites", the favourited properties linked to the account are displayed.
- [ ] #169 Create a page display when there are no favourited properties.
