### ISSUE TITLE
Managing Accounts User Story

### ISSUE THREAD

**Issue by mylinhtang** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#23]
As a buyer/renter/broker/admin, I want to setup an account so that I can include all my information and can be easily communicated with in order to conduct my business adequately.

Acceptance Criteria:

I want the ability to set my name so I can be identified.
I want the ability to choose if I am a buyer, renter or broker.
I want the ability to set a password for security.
I want the ability to set my email so I can be contacted.
The ability to modify name/password/email if necessary.

Task Breakdown:
- [ ] #57 Sign up / Sign in button in Accounts page
- [ ] #78  New page appears to sign in when Sign up / Sign in button is clicked.
- [ ] #58 Form to fill in if account already exists (email, password).
- [ ] #79 Create a button to sign up.
- [ ] #59 Form to fill in for sign up (email, password, full name, three buttons for type of user created).
- [ ] #60  Hash password when logging in / requirements for password.
- [ ] #61 Look if username/password matches a user in the database.
- [ ] #62 Display message if username/password incorrect.
- [ ] #63 When creating an account, it will also create an object in the database

**Comment by Toterino** [comment]
Acceptance flow test 

1 - The user signs up with a valid email and password and a notification appears mentioning that the creation was successful #57 #59 #63
2 - If the user tries to sign up again with the same email (or any other email that is already used), there will be an error popup #62 #61

**Comment by Toterino** [comment]
Acceptance flow test

1- The user signs in with a valid username and password and gets redirected to the home page #57 #78
2- If the user enters the wrong password, an alert saying 'wrong password" appears #62
3 - If user enters an email that does not have an account, display that the account does not exist.
