### ISSUE TITLE
Search for Properties User Story

### ISSUE THREAD

**Issue by mylinhtang** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#24]
As a buyer and/or a renter, I want to search for relevant properties based on specific criteria such as location, number of beds/baths, price range, living and lot area dimensions and building type so that I can filter the best-fitted properties for my needs.

Acceptance Criteria:
I want to be able to look at a complete collection of houses that are on sale/for rent.
I want the ability to look and filter these properties according to the attributes I select

Task Breakdown:
- [ ] #47 Create the little square templates for each property for the home page
- [ ] #48 Find the filtered properties in the database
- [ ] #49 Price filtering: Slider
- [ ] #50 Location filtering: Check-boxes
- [ ] #51 Dimensions: Drop down
- [ ] #52Number of beds/baths: Clicker
- [ ] #53 Type of property: Check-boxes
- [ ] #54 Display all the available properties
- [ ] #55 When clicking on a property, another page with more detailed information pops up such as more images, price, mortgage calculator (including a request button).
- [ ] #56 Full Page Template with More Detail each property should have.

**Comment by Toterino** [comment]
Acceptance test 

1 - The user can look at all the available properties. #54
2 - The user can filter properties based on different attributes of the houses including location, type, number of bedrooms, number of bathrooms, dimensions and the price range. #48 #49 #50 #51 #52 #53

**Comment by Toterino** [comment]
Acceptance test

1 - The user can open a detailed page of the property displaying more details #55 #56
