### ISSUE TITLE
Request Visits User Story

### ISSUE THREAD

**Issue by mylinhtang** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#25]
As a home buyer/renter, I want to be able to click on a particular building and request a visit at an available date that suits me

Acceptance criteria:
I want to click on the request button and have a date system with available dates appear
I want to be able to choose a date and submit my request to a broker

Task Breakdown:
- [ ] #64 On each property page, create a request visit button.
- [ ] #65 When the button is clicked, a calendar system appears and user should be able to click on a date and submit.
- [ ] #66 Date is saved in the database.
- [ ] #67 Request sent to broker.
- [ ] #68 Display visit request on the broker's page.
- [ ] #107 Reschedule visit request.
- [ ] #108 Cancel visit request.

**Comment by Toterino** [comment]
Acceptance test 

1 - The user (homebuyer/renter) can request a visit to the property by clicking on the button. The user can choose a date and a time that suits them. #64 #65 #66

**Comment by Toterino** [comment]
Acceptance test

1 - The broker can see the request in their "manage visit request" page and can see the details of the request #68
