### ISSUE TITLE
CRUD operations on properties User Story

### ISSUE THREAD

**Issue by mylinhtang** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#26]
As a real estate broker, I want to be able to list and manage properties on behalf of my clients, so that I can simplify the real-estate workflow and efficiently manage the selling process of the properties.

Acceptance criteria:
I want to be able to create property listings and add a description with relevant details to the property.
I want to be able to edit property listings so that I can update information regarding the property.
After listing my properties, I want to be able to view all my listings and read the descriptions.
I want to be able to delete the property listings that are no longer available.

Task Breakdown:
- [ ] #69 Have a "create property" button on the account page
- [ ] #69 Once clicked, the page will prompt for broker to enter information and pictures of property
- [ ] #70 Property information saved in database.
- [ ] #71
- [ ] #72 Create a "delete" button.
- [ ] #72 Clicking on "delete" button will erase the property from the database.
- [ ] #88 Clicking on "Manage Properties" will display the current broker's managed properties.

**Comment by Toterino** [comment]
Acceptance test

1 - The broker can create a property by adding its details onto the form #69 #70
2 - The broker can view all their properties in a page #88

**Comment by Toterino** [comment]
Acceptance test

1 - The broker can edit their properties and refill the form. #71
2 - The broker can delete that property which gets deleted from the database #72
