### ISSUE TITLE
CRUD operations on brokers User Story

### ISSUE THREAD

**Issue by mylinhtang** [Mohamed-Redouane/-UrbanGate-soen341projectF2023-#27]
As an admin, I want to be able to manage the broker accounts so that I can properly moderate the system's users to insure security and a pleasant user experience.

Acceptance Criteria:
Read a list of existing broker accounts so that I can have an overview of all brokers.
I want to be able to update the information of broker accounts in the case that a change of status or details is needed.
I want to be able to delete broker accounts in the case that they conduct business insincerely.

Task Breakdown:
- [ ] #73 Have an "edit brokers" button on account page that can manage/delete broker information
- [ ] #73 Clicking "edit brokers" leads to a new page with a listing of all brokers.
- [ ] #74 Create "Create broker" button.
- [ ] #74 Clicking on "create broker" button will pop a new form to fill (email, name, password).
- [ ] #75 Data on new broker is saved in database.
- [ ] #76 Create "Update broker" button.
- [ ] #76 Clicking "Update broker" button will allow to change information about the broker.
- [ ] #76 Create "save" button on update broker form will save new information in database.
- [ ] #76 Create "Cancel" button on the update broker form will erase all new information edited in the form.
- [ ] #77 Create "Delete broker" button.
- [ ] #77 Clicking on "delete broker" will erase the broker's information in the database.

**Comment by Toterino** [comment]
Acceptance test

1 - The admin can create brokers by filling a form. #74 #75
2 - The admin can see all the brokers in the 'manage brokers' page.

**Comment by Toterino** [comment]
Acceptance test

1 - The admin can edit broker details by clicking on a button. #73 #76 
2 - The admin can delete brokers. #77
